{
  "hash": "c105c693850526222eb08d519be3fa0a",
  "result": {
    "engine": "knitr",
    "markdown": "# Regression models {#reg}\n\n\n\n\n\n\n\n\n\nLet's consider a (fictional) dataset with only five cases. We can create a dataset using the `data.frame` command. Our dataset initially has just two variables: `var1` and `var2`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1 <- data.frame(id   = 1:8,\n                   var1 = c(2,1,2,5,7, 8, 9,5),\n                   var2 = c(2,2,1,9,7, 4,25,3),\n                   educ = c(3,1,2,2,1, 3, 2,-1),\n                   gend = c(2,1,1,2,1,2,1,2),\n                   x    = c(2,1,2,4,1,NA,NA,NA) )\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id var1 var2 educ gend  x\n1  1    2    2    3    2  2\n2  2    1    2    1    1  1\n3  3    2    1    2    1  2\n4  4    5    9    2    2  4\n5  5    7    7    1    1  1\n6  6    8    4    3    2 NA\n7  7    9   25    2    1 NA\n8  8    5    3   -1    2 NA\n```\n\n\n:::\n:::\n\n\n\n\nHere is the translation of the provided text into English:\n\n---\n\n## Regression Models with `lm()` {#lm1}\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nRegression models in R can be created with `lm()`. Here, we specify the variable for the y-axis (the *dependent* variable) and, after a `~`, the variable for the x-axis (the *independent* variable). We will discuss the interpretation of the results in the coming weeks.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(var2 ~ var1, data = dat1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1)\n\nCoefficients:\n(Intercept)         var1  \n     -2.340        1.839  \n```\n\n\n:::\n:::\n\n\n\n\nThe value under `var1` indicates *how much the line changes up/down per \"step to the right\"*. Thus, the line increases by 1.8389662 for each unit of `var1`. We can store the results under `m1`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(var2 ~ var1, data = dat1)  \n```\n:::\n\n\n\n\nWith `summary()`, we get a regression table:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-8.372 -3.613  0.162  2.234 10.789 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept)  -2.3400     4.3454  -0.538   0.6096  \nvar1          1.8390     0.7727   2.380   0.0548 .\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.127 on 6 degrees of freedom\nMultiple R-squared:  0.4856,\tAdjusted R-squared:  0.3999 \nF-statistic: 5.664 on 1 and 6 DF,  p-value: 0.05477\n```\n\n\n:::\n:::\n\n\n\n\n`m1` contains all the information about the model, and `$coefficients` is particularly helpful:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)        var1 \n  -2.339960    1.838966 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(m1)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate Std. Error    t value   Pr(>|t|)\n(Intercept) -2.339960  4.3453801 -0.5384938 0.60961706\nvar1         1.838966  0.7727028  2.3799139 0.05477457\n```\n\n\n:::\n:::\n\n\n\n\nWe can view the individual values with `View(m1)`:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"jsonedit html-widget html-fill-item\" id=\"htmlwidget-d43ec9e2a1836b48d84e\" style=\"width:100%;height:10%;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d43ec9e2a1836b48d84e\">{\"x\":{\"data\":{\"coefficients\":{\"(Intercept)\":-2.339960238568588,\"var1\":1.8389662027833},\"residuals\":{\"1\":0.6620278330019898,\"2\":2.500994035785288,\"3\":-0.337972166998012,\"4\":2.145129224652087,\"5\":-3.532803180914513,\"6\":-8.371769383697812,\"7\":10.78926441351889,\"8\":-3.854870775347913},\"effects\":{\"(Intercept)\":-18.73832970144351,\"var1\":14.58185403838686,\"3\":-0.9582613924451362,\"4\":2.156699894051008,\"5\":-3.099992581618229,\"6\":-7.728338819452848,\"7\":11.64331494271253,\"8\":-3.843300105948992},\"rank\":2,\"fitted.values\":{\"1\":1.33797216699801,\"2\":-0.5009940357852876,\"3\":1.337972166998012,\"4\":6.854870775347913,\"5\":10.53280318091451,\"6\":12.37176938369781,\"7\":14.21073558648111,\"8\":6.854870775347913},\"assign\":[0,1],\"qr\":{\"qr\":[[-2.82842712474619,-13.78858223313767],[0.3535533905932737,7.929375763576853],[0.3535533905932737,0.2678696183419504],[0.3535533905932737,-0.1104703783297086],[0.3535533905932737,-0.3626970427774812],[0.3535533905932737,-0.4888103750013675],[0.3535533905932737,-0.6149237072252539],[0.3535533905932737,-0.1104703783297086]],\"qraux\":[1.353553390593274,1.393982950565837],\"pivot\":[1,2],\"tol\":1e-07,\"rank\":2},\"df.residual\":6,\"xlevels\":{},\"call\":{},\"terms\":{},\"model\":{\"var2\":[2,2,1,9,7,4,25,3],\"var1\":[2,1,2,5,7,8,9,5]}},\"options\":{\"mode\":\"view\",\"modes\":[\"text\",\"tree\",\"table\"]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\nFor example, `fitted.values` contains the predicted values for each case.\n\n\n### [Exercise](#reg1) \n\n## Calculating Models for Specific Cases\n\nIf we want to recalculate the model, we have two options:\n\n### Create a New Data Frame\n\nWe can keep multiple `data.frame` objects in memory in R. Thus, we can easily create a new `data.frame` containing only observations with `var2 < 20` and use this for our `lm()` command:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1_u20 <- dat1 %>% filter(var2 < 20)\nm2a <- lm(var2 ~ var1, data = dat1_u20)\nsummary(m2a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1_u20)\n\nResiduals:\n      1       2       3       4       5       6       7 \n-0.4737  0.1941 -1.4737  4.5230  1.1875 -2.4803 -1.4770 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   1.1382     1.9217   0.592    0.579\nvar1          0.6678     0.3877   1.722    0.146\n\nResidual standard error: 2.555 on 5 degrees of freedom\nMultiple R-squared:  0.3724,\tAdjusted R-squared:  0.2469 \nF-statistic: 2.967 on 1 and 5 DF,  p-value: 0.1456\n```\n\n\n:::\n:::\n\n\n\n\n### Filter Directly in `lm()`\n\nWe can also incorporate the `filter()` command directly into the `data=` argument of `lm()`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2b <- lm(var2 ~ var1, data = dat1 %>% filter(var2 < 20))\nsummary(m2b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1 %>% filter(var2 < 20))\n\nResiduals:\n      1       2       3       4       5       6       7 \n-0.4737  0.1941 -1.4737  4.5230  1.1875 -2.4803 -1.4770 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   1.1382     1.9217   0.592    0.579\nvar1          0.6678     0.3877   1.722    0.146\n\nResidual standard error: 2.555 on 5 degrees of freedom\nMultiple R-squared:  0.3724,\tAdjusted R-squared:  0.2469 \nF-statistic: 2.967 on 1 and 5 DF,  p-value: 0.1456\n```\n\n\n:::\n:::\n\n\n\n\n## Regression tables\n\nIf we want to compare these different models, a table is a good option.\n\nThere are numerous alternatives for creating regression tables, and my personal favorite is `modelsummary()` from the eponymous package [{modelsummary}](https://vincentarelbundock.github.io/modelsummary/). It handles (almost) all types of models and offers a wide range of features, including [Word output](#14_tabellenexport.qmd) (more on this later) and coefficient plots (which we will also cover). Additionally, the [documentation](https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html) is excellent.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfdz_install(\"modelsummary\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(modelsummary)\nmodelsummary(list(m1,m2a,m2b))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!DOCTYPE html> \n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>tinytable_vo6671bg88ivlj3vlakp</title>\n    <style>\n.table td.tinytable_css_kqcyiucmq9fkn5y70j5d, .table th.tinytable_css_kqcyiucmq9fkn5y70j5d {    border-bottom: solid 0.1em #d3d8dc; }\n.table td.tinytable_css_go7ko01m0hpzjj8qh6qy, .table th.tinytable_css_go7ko01m0hpzjj8qh6qy {    text-align: left; }\n.table td.tinytable_css_k71ii5t1lvx0kd6g6z6j, .table th.tinytable_css_k71ii5t1lvx0kd6g6z6j {    text-align: center; }\n.table td.tinytable_css_r5mmcz6ljz9yteuwk1hx, .table th.tinytable_css_r5mmcz6ljz9yteuwk1hx {    text-align: center; }\n.table td.tinytable_css_8idlv0dkxoolb16lmxsc, .table th.tinytable_css_8idlv0dkxoolb16lmxsc {    text-align: center; }\n.table td.tinytable_css_eymitlcfqxwh11v86bmh, .table th.tinytable_css_eymitlcfqxwh11v86bmh {    border-bottom: solid 0.05em black; }\n    </style>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=es6\"></script>\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n  </head>\n\n  <body>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_vo6671bg88ivlj3vlakp\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">(1)</th>\n                <th scope=\"col\">(2)</th>\n                <th scope=\"col\">(3)</th>\n              </tr>\n        </thead>\n        \n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>-2.340 </td>\n                  <td>1.138  </td>\n                  <td>1.138  </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>(4.345)</td>\n                  <td>(1.922)</td>\n                  <td>(1.922)</td>\n                </tr>\n                <tr>\n                  <td>var1       </td>\n                  <td>1.839  </td>\n                  <td>0.668  </td>\n                  <td>0.668  </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>(0.773)</td>\n                  <td>(0.388)</td>\n                  <td>(0.388)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.   </td>\n                  <td>8      </td>\n                  <td>7      </td>\n                  <td>7      </td>\n                </tr>\n                <tr>\n                  <td>R2         </td>\n                  <td>0.486  </td>\n                  <td>0.372  </td>\n                  <td>0.372  </td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.    </td>\n                  <td>0.400  </td>\n                  <td>0.247  </td>\n                  <td>0.247  </td>\n                </tr>\n                <tr>\n                  <td>AIC        </td>\n                  <td>55.4   </td>\n                  <td>36.6   </td>\n                  <td>36.6   </td>\n                </tr>\n                <tr>\n                  <td>BIC        </td>\n                  <td>55.6   </td>\n                  <td>36.5   </td>\n                  <td>36.5   </td>\n                </tr>\n                <tr>\n                  <td>Log.Lik.   </td>\n                  <td>-24.702</td>\n                  <td>-15.321</td>\n                  <td>-15.321</td>\n                </tr>\n                <tr>\n                  <td>F          </td>\n                  <td>5.664  </td>\n                  <td>2.967  </td>\n                  <td>2.967  </td>\n                </tr>\n                <tr>\n                  <td>RMSE       </td>\n                  <td>5.31   </td>\n                  <td>2.16   </td>\n                  <td>2.16   </td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n\n    <script>\n      function styleCell_tinytable_91qp53x0kggy7rust4f1(i, j, css_id) {\n        var table = document.getElementById(\"tinytable_vo6671bg88ivlj3vlakp\");\n        table.rows[i].cells[j].classList.add(css_id);\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_vo6671bg88ivlj3vlakp');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_tinytable_91qp53x0kggy7rust4f1(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_vo6671bg88ivlj3vlakp\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 0, 'tinytable_css_kqcyiucmq9fkn5y70j5d') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 1, 'tinytable_css_kqcyiucmq9fkn5y70j5d') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 2, 'tinytable_css_kqcyiucmq9fkn5y70j5d') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 3, 'tinytable_css_kqcyiucmq9fkn5y70j5d') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(1, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(2, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(3, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(5, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(6, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(7, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(8, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(9, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(10, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(11, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(12, 0, 'tinytable_css_go7ko01m0hpzjj8qh6qy') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(1, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(2, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(3, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(5, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(6, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(7, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(8, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(9, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(10, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(11, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(12, 1, 'tinytable_css_k71ii5t1lvx0kd6g6z6j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(1, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(2, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(3, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(5, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(6, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(7, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(8, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(9, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(10, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(11, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(12, 2, 'tinytable_css_r5mmcz6ljz9yteuwk1hx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(0, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(1, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(2, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(3, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(5, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(6, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(7, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(8, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(9, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(10, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(11, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(12, 3, 'tinytable_css_8idlv0dkxoolb16lmxsc') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 0, 'tinytable_css_eymitlcfqxwh11v86bmh') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 1, 'tinytable_css_eymitlcfqxwh11v86bmh') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 2, 'tinytable_css_eymitlcfqxwh11v86bmh') })\nwindow.addEventListener('load', function () { styleCell_tinytable_91qp53x0kggy7rust4f1(4, 3, 'tinytable_css_eymitlcfqxwh11v86bmh') })\n    </script>\n\n  </body>\n\n</html>\n```\n\n:::\n:::\n\n\n\n\nWe will delve a bit more into the customization options for `{modelsummary}` later, but here are two key options for now:\n\n+ By using `stars = T`, we can display the significance levels with the common star codes (`*`: p < .05, etc.)\n+ By using `gof_omit = \"IC|RM|Log\"`, we can hide the goodness of fit statistics that have `IC`, `RM`, or `Log` in their names (such as `AIC`, `BIC`, `RMSE`, and `LogLikelihood`)\n+ By using `\"Name\" =` in `list()`, we can specify names:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"m1\"=m1,\"m2a\"=m2a,\"m2b\"=m2b),stars = T,gof_omit = \"IC|RM|Log\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<!DOCTYPE html> \n<html lang=\"en\">\n  <head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>tinytable_od6ezk9exwtmeo62j3c1</title>\n    <style>\n.table td.tinytable_css_fg6pkxxj886246ax2rsv, .table th.tinytable_css_fg6pkxxj886246ax2rsv {    border-bottom: solid 0.1em #d3d8dc; }\n.table td.tinytable_css_ahld8s1ihve0soc6ymeu, .table th.tinytable_css_ahld8s1ihve0soc6ymeu {    text-align: left; }\n.table td.tinytable_css_9hp8nn7gdkjoshzrmnmi, .table th.tinytable_css_9hp8nn7gdkjoshzrmnmi {    text-align: center; }\n.table td.tinytable_css_diidjpx7flsta4055kwx, .table th.tinytable_css_diidjpx7flsta4055kwx {    text-align: center; }\n.table td.tinytable_css_0ohyzytffqd6z6i5xy4j, .table th.tinytable_css_0ohyzytffqd6z6i5xy4j {    text-align: center; }\n.table td.tinytable_css_prwl28th6ukehb21c9ir, .table th.tinytable_css_prwl28th6ukehb21c9ir {    border-bottom: solid 0.05em black; }\n    </style>\n    <script src=\"https://polyfill.io/v3/polyfill.min.js?features=es6\"></script>\n    <script id=\"MathJax-script\" async src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"></script>\n    <script>\n    MathJax = {\n      tex: {\n        inlineMath: [['$', '$'], ['\\\\(', '\\\\)']]\n      },\n      svg: {\n        fontCache: 'global'\n      }\n    };\n    </script>\n  </head>\n\n  <body>\n    <div class=\"container\">\n      <table class=\"table table-borderless\" id=\"tinytable_od6ezk9exwtmeo62j3c1\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        <thead>\n        \n              <tr>\n                <th scope=\"col\"> </th>\n                <th scope=\"col\">m1</th>\n                <th scope=\"col\">m2a</th>\n                <th scope=\"col\">m2b</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='4'>+ p < 0.1, * p < 0.05, ** p < 0.01, *** p < 0.001</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td>(Intercept)</td>\n                  <td>-2.340 </td>\n                  <td>1.138  </td>\n                  <td>1.138  </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>(4.345)</td>\n                  <td>(1.922)</td>\n                  <td>(1.922)</td>\n                </tr>\n                <tr>\n                  <td>var1       </td>\n                  <td>1.839+ </td>\n                  <td>0.668  </td>\n                  <td>0.668  </td>\n                </tr>\n                <tr>\n                  <td>           </td>\n                  <td>(0.773)</td>\n                  <td>(0.388)</td>\n                  <td>(0.388)</td>\n                </tr>\n                <tr>\n                  <td>Num.Obs.   </td>\n                  <td>8      </td>\n                  <td>7      </td>\n                  <td>7      </td>\n                </tr>\n                <tr>\n                  <td>R2         </td>\n                  <td>0.486  </td>\n                  <td>0.372  </td>\n                  <td>0.372  </td>\n                </tr>\n                <tr>\n                  <td>R2 Adj.    </td>\n                  <td>0.400  </td>\n                  <td>0.247  </td>\n                  <td>0.247  </td>\n                </tr>\n                <tr>\n                  <td>F          </td>\n                  <td>5.664  </td>\n                  <td>2.967  </td>\n                  <td>2.967  </td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n\n    <script>\n      function styleCell_tinytable_s6yy62epnl43j1se1y5c(i, j, css_id) {\n        var table = document.getElementById(\"tinytable_od6ezk9exwtmeo62j3c1\");\n        table.rows[i].cells[j].classList.add(css_id);\n      }\n      function insertSpanRow(i, colspan, content) {\n        var table = document.getElementById('tinytable_od6ezk9exwtmeo62j3c1');\n        var newRow = table.insertRow(i);\n        var newCell = newRow.insertCell(0);\n        newCell.setAttribute(\"colspan\", colspan);\n        // newCell.innerText = content;\n        // this may be unsafe, but innerText does not interpret <br>\n        newCell.innerHTML = content;\n      }\n      function spanCell_tinytable_s6yy62epnl43j1se1y5c(i, j, rowspan, colspan) {\n        var table = document.getElementById(\"tinytable_od6ezk9exwtmeo62j3c1\");\n        const targetRow = table.rows[i];\n        const targetCell = targetRow.cells[j];\n        for (let r = 0; r < rowspan; r++) {\n          // Only start deleting cells to the right for the first row (r == 0)\n          if (r === 0) {\n            // Delete cells to the right of the target cell in the first row\n            for (let c = colspan - 1; c > 0; c--) {\n              if (table.rows[i + r].cells[j + c]) {\n                table.rows[i + r].deleteCell(j + c);\n              }\n            }\n          }\n          // For rows below the first, delete starting from the target column\n          if (r > 0) {\n            for (let c = colspan - 1; c >= 0; c--) {\n              if (table.rows[i + r] && table.rows[i + r].cells[j]) {\n                table.rows[i + r].deleteCell(j);\n              }\n            }\n          }\n        }\n        // Set rowspan and colspan of the target cell\n        targetCell.rowSpan = rowspan;\n        targetCell.colSpan = colspan;\n      }\n\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 0, 'tinytable_css_fg6pkxxj886246ax2rsv') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 1, 'tinytable_css_fg6pkxxj886246ax2rsv') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 2, 'tinytable_css_fg6pkxxj886246ax2rsv') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 3, 'tinytable_css_fg6pkxxj886246ax2rsv') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(1, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(2, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(3, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(5, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(6, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(7, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(8, 0, 'tinytable_css_ahld8s1ihve0soc6ymeu') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(1, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(2, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(3, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(5, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(6, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(7, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(8, 1, 'tinytable_css_9hp8nn7gdkjoshzrmnmi') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(1, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(2, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(3, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(5, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(6, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(7, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(8, 2, 'tinytable_css_diidjpx7flsta4055kwx') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(0, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(1, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(2, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(3, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(5, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(6, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(7, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(8, 3, 'tinytable_css_0ohyzytffqd6z6i5xy4j') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 0, 'tinytable_css_prwl28th6ukehb21c9ir') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 1, 'tinytable_css_prwl28th6ukehb21c9ir') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 2, 'tinytable_css_prwl28th6ukehb21c9ir') })\nwindow.addEventListener('load', function () { styleCell_tinytable_s6yy62epnl43j1se1y5c(4, 3, 'tinytable_css_prwl28th6ukehb21c9ir') })\n    </script>\n\n  </body>\n\n</html>\n```\n\n:::\n:::\n\n\n\n\nThe `output =` option allows us to export the modelsummary as `.docx`-file:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelsummary(list(\"m1\"=m1,\"m2a\"=m2a,\"m2b\"=m2b),stars = T,gof_omit = \"IC|RM|Log\",output = \"./results/Regression_table.docx\")\n```\n:::\n\n\n\n\n### [Exercise](#reg2)\n\n## Categorical Independent Variables\n\nOf course, we can also include categorical independent variables in our model. However, we need to define the relevant variables as `factors` to inform R that the numeric values should not be interpreted numerically. \n\nFor instance, in our small example, `educ` represents education levels where 1 stands for basic education, 2 for intermediate, and 3 for high education.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id var1 var2 educ gend  x\n1  1    2    2    3    2  2\n2  2    1    2    1    1  1\n3  3    2    1    2    1  2\n4  4    5    9    2    2  4\n5  5    7    7    1    1  1\n6  6    8    4    3    2 NA\n7  7    9   25    2    1 NA\n8  8    5    3   -1    2 NA\n```\n\n\n:::\n\n```{.r .cell-code}\nm3 <- lm(var2 ~ factor(educ), dat1)\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ factor(educ), data = dat1)\n\nResiduals:\n         1          2          3          4          5          6          7 \n-1.000e+00 -2.500e+00 -1.067e+01 -2.667e+00  2.500e+00  1.000e+00  1.333e+01 \n         8 \n-1.277e-15 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)\n(Intercept)    3.000e+00  8.848e+00   0.339    0.752\nfactor(educ)1  1.500e+00  1.084e+01   0.138    0.897\nfactor(educ)2  8.667e+00  1.022e+01   0.848    0.444\nfactor(educ)3 -1.088e-15  1.084e+01   0.000    1.000\n\nResidual standard error: 8.848 on 4 degrees of freedom\nMultiple R-squared:  0.2848,\tAdjusted R-squared:  -0.2516 \nF-statistic: 0.531 on 3 and 4 DF,  p-value: 0.685\n```\n\n\n:::\n:::\n\n\n\n\nIt's even better if we label `educ` beforehand:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$ed_fct <- factor(dat1$educ, levels = 1:3,\n                        labels = c(\"basic\", \"medium\", \"high\"))\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id var1 var2 educ gend  x ed_fct\n1  1    2    2    3    2  2   high\n2  2    1    2    1    1  1  basic\n3  3    2    1    2    1  2 medium\n4  4    5    9    2    2  4 medium\n5  5    7    7    1    1  1  basic\n6  6    8    4    3    2 NA   high\n7  7    9   25    2    1 NA medium\n8  8    5    3   -1    2 NA   <NA>\n```\n\n\n:::\n:::\n\n\n\n\nThen use the `factor` in the regression command:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(var2 ~ ed_fct, dat1)\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ ed_fct, data = dat1)\n\nResiduals:\n      1       2       3       4       5       6       7 \n -1.000  -2.500 -10.667  -2.667   2.500   1.000  13.333 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)\n(Intercept)     4.500      6.257   0.719    0.512\ned_fctmedium    7.167      8.077   0.887    0.425\ned_fcthigh     -1.500      8.848  -0.170    0.874\n\nResidual standard error: 8.848 on 4 degrees of freedom\n  (1 Beobachtung als fehlend gelöscht)\nMultiple R-squared:  0.2594,\tAdjusted R-squared:  -0.1109 \nF-statistic: 0.7005 on 2 and 4 DF,  p-value: 0.5485\n```\n\n\n:::\n:::\n\n\n\n\n+ Compared to `educ = basic`, the predicted value for `var2` when `educ = medium` is 7.17 higher.\n\n+ Compared to `educ = basic`, the predicted value for `var2` when `educ = high` is -1.5 higher.\n\nWe can also change the reference category:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$ed_fct <- relevel(dat1$ed_fct, ref = \"medium\")\nm3b <- lm(var2 ~ ed_fct, dat1)\nsummary(m3b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ ed_fct, data = dat1)\n\nResiduals:\n      1       2       3       4       5       6       7 \n -1.000  -2.500 -10.667  -2.667   2.500   1.000  13.333 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)  \n(Intercept)   11.667      5.109   2.284   0.0844 .\ned_fctbasic   -7.167      8.077  -0.887   0.4251  \ned_fcthigh    -8.667      8.077  -1.073   0.3437  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.848 on 4 degrees of freedom\n  (1 Beobachtung als fehlend gelöscht)\nMultiple R-squared:  0.2594,\tAdjusted R-squared:  -0.1109 \nF-statistic: 0.7005 on 2 and 4 DF,  p-value: 0.5485\n```\n\n\n:::\n:::\n\n\n\n\n+ Compared to `educ = medium`, the predicted value for `var2` when `educ = basic` is 7.17 lower.\n\n+ Compared to `educ = medium`, the predicted value for `var2` when `educ = high` is 8.67 lower.\n\n### [Exercise](#reg3)\n\n## Multiple Independent Variables\n\nTo include multiple independent variables in our regression models, we specify them using `+`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- lm(var2 ~ ed_fct + var1, dat1)\nsummary(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ ed_fct + var1, data = dat1)\n\nResiduals:\n     1      2      3      4      5      6      7 \n 4.258  2.758 -4.824 -2.082 -2.758 -4.258  6.907 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)\n(Intercept)   2.3187     5.8227   0.398    0.717\ned_fctbasic  -4.8297     6.0381  -0.800    0.482\ned_fcthigh   -8.0824     5.9411  -1.360    0.267\nvar1          1.7527     0.8347   2.100    0.127\n\nResidual standard error: 6.501 on 3 degrees of freedom\n  (1 Beobachtung als fehlend gelöscht)\nMultiple R-squared:  0.7002,\tAdjusted R-squared:  0.4003 \nF-statistic: 2.335 on 3 and 3 DF,  p-value: 0.2521\n```\n\n\n:::\n:::\n\n\n\n\n## Coefficient Plots {#modelplot}\n\n\n\n\n\n\n\n\n\nIn addition to regression tables, [`{modelsummary}`](https://vincentarelbundock.github.io/modelsummary/articles/modelplot.html) provides the `modelplot()` function, which makes it easy to create coefficient plots from one or more models:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelplot(m4)\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-17-1.png){width=50% height=50%}\n:::\n:::\n\n\n\n\nFor model comparison, simply provide the models in a named `list`, and you can further customize the plot with the usual `{ggplot2}` commands:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelplot(list(\"Model 1\" = m1,\n               \"Model 4\" = m4))\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-18-1.png){width=50% height=50%}\n:::\n:::\n\n\n\n\nWith `coef_map`, you can assign labels to the coefficients (note that `(Intercept)` does not get a name and is therefore omitted):\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelplot(list(\"Model 1\" = m1,\n               \"Model 4\" = m4),\n          coef_map = c(\"var1\" = \"Name for var1\",\n                       \"ed_fcthigh\" = \"Higher Education\",\n                       \"ed_fctbasic\" = \"Basic Education\"\n                          ))\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-19-1.png){width=50% height=50%}\n:::\n:::\n\n\n\n\nYou can also further customize the plot with the usual `{ggplot2}` commands:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelplot(list(\"Model 1\" = m1,\n               \"Model 4\" = m4),\n          coef_map = c(\"var1\" = \"Name for var1\",\n                       \"ed_fcthigh\" = \"Higher Education\",\n                       \"ed_fctbasic\" = \"Basic\\nEducation\")) + # \\n inserts a line break\n  geom_vline(aes(xintercept = 0), linetype = \"dashed\", color = \"grey40\") +  # Add a 0 line\n  scale_color_manual(values = c(\"orange\", \"navy\")) +\n  theme_minimal(base_size = 15, base_family = \"serif\") \n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-20-1.png){width=50% height=50%}\n:::\n:::\n\n\n\n\nWith `{broom}`, you can also create a `data.frame` from the regression results and create the `ggplot` entirely yourself - [see appendix](#broomplt).\n\n:::{.callout-tip}\n### margins: `{marginaleffects}` {.unnumbered}\n\nAlternative visual summaries of regression results rely on marginal effects, contrasts, elasticities, or predictions. \nFor all of these metric, see the [`{marginaleffects}`](https://marginaleffects.com/) package.\n[There's a special chapter for replicating Stata's margins](https://marginaleffects.com/vignettes/alternative_software.html#stata) \n\n:::\n\n### [Exercise](#reg4)\n\n\n## Exercises\n\nUse the following subset of the PASS CampusFile:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npend_ue08 <- haven::read_dta(\"./orig/PENDDAT_cf_W13.dta\") %>% \n  filter(welle == 13, netges > 0, azges1 > 0, schul2 > 1, palter > 0)\n```\n:::\n\n\n\n\n### Regression model {#reg1}\n\n+ Create an object `mod1` with a linear regression model (`lm`) where `netges` (monthly net income in EUR) is the dependent variable and `azges1` (working hours) is the independent variable! (see [here](#lm1))\n+ Examine the results of `mod1` - what can you infer about the relationship between `netges` and `azges1`?\n\n### Categorical Independent Variables {#reg3}\n\n+ Create a regression model with the income of respondents (`netges`) as the dependent variable and the education level of the respondents `schul` as the independent variable:\n\n\n\n\n::: {.cell .plain}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"uvhamqcdhm\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#uvhamqcdhm table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#uvhamqcdhm thead, #uvhamqcdhm tbody, #uvhamqcdhm tfoot, #uvhamqcdhm tr, #uvhamqcdhm td, #uvhamqcdhm th {\n  border-style: none;\n}\n\n#uvhamqcdhm p {\n  margin: 0;\n  padding: 0;\n}\n\n#uvhamqcdhm .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 14px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#uvhamqcdhm .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#uvhamqcdhm .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#uvhamqcdhm .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#uvhamqcdhm .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#uvhamqcdhm .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#uvhamqcdhm .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#uvhamqcdhm .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#uvhamqcdhm .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#uvhamqcdhm .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#uvhamqcdhm .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#uvhamqcdhm .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#uvhamqcdhm .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#uvhamqcdhm .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#uvhamqcdhm .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uvhamqcdhm .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#uvhamqcdhm .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#uvhamqcdhm .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#uvhamqcdhm .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uvhamqcdhm .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#uvhamqcdhm .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uvhamqcdhm .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#uvhamqcdhm .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uvhamqcdhm .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#uvhamqcdhm .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#uvhamqcdhm .gt_left {\n  text-align: left;\n}\n\n#uvhamqcdhm .gt_center {\n  text-align: center;\n}\n\n#uvhamqcdhm .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#uvhamqcdhm .gt_font_normal {\n  font-weight: normal;\n}\n\n#uvhamqcdhm .gt_font_bold {\n  font-weight: bold;\n}\n\n#uvhamqcdhm .gt_font_italic {\n  font-style: italic;\n}\n\n#uvhamqcdhm .gt_super {\n  font-size: 65%;\n}\n\n#uvhamqcdhm .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#uvhamqcdhm .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#uvhamqcdhm .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#uvhamqcdhm .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#uvhamqcdhm .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#uvhamqcdhm .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#uvhamqcdhm .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#uvhamqcdhm .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#uvhamqcdhm div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout: fixed;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:80px;\"/>\n    <col/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"value\">value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\">label</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"value\" class=\"gt_row gt_left\"><div data-qmd-base64=\"YDJg\"><div class='gt_from_md'><p><code>2</code></p>\n</div></div></td>\n<td headers=\"label\" class=\"gt_row gt_left\">Finished school without degree</td></tr>\n    <tr><td headers=\"value\" class=\"gt_row gt_left\"><div data-qmd-base64=\"YDNg\"><div class='gt_from_md'><p><code>3</code></p>\n</div></div></td>\n<td headers=\"label\" class=\"gt_row gt_left\">School incorporating physically or mentally disabled children (Sonderschulabschluss)</td></tr>\n    <tr><td headers=\"value\" class=\"gt_row gt_left\"><div data-qmd-base64=\"YDRg\"><div class='gt_from_md'><p><code>4</code></p>\n</div></div></td>\n<td headers=\"label\" class=\"gt_row gt_left\">Lower secondary school (Hauptschulabschluss)</td></tr>\n    <tr><td headers=\"value\" class=\"gt_row gt_left\"><div data-qmd-base64=\"YDVg\"><div class='gt_from_md'><p><code>5</code></p>\n</div></div></td>\n<td headers=\"label\" class=\"gt_row gt_left\">Intermediate secondary school (Realschulabschluss, Mittlere Reife)</td></tr>\n    <tr><td headers=\"value\" class=\"gt_row gt_left\"><div data-qmd-base64=\"YDZg\"><div class='gt_from_md'><p><code>6</code></p>\n</div></div></td>\n<td headers=\"label\" class=\"gt_row gt_left\">Upper secondary Fachoberschule, Fachhochschulreife)</td></tr>\n    <tr><td headers=\"value\" class=\"gt_row gt_left\"><div data-qmd-base64=\"YDdg\"><div class='gt_from_md'><p><code>7</code></p>\n</div></div></td>\n<td headers=\"label\" class=\"gt_row gt_left\">General/subject-specific upper secondary school (Hochschulreife)</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n+ Ensure that `schul2` is defined as a `factor`. Assign the labels \"No degree\", \"Special education School\", \"Secondary School\", \"Intermediate Diploma\", \"Vocational School\", \"Abitur\" to levels 2-7 and save the `factor` as a variable `schul2_fct` in your `data.frame` - see the code help below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npend_ue08$schul2_fct <-  \n  factor(pend_ue08$schul2, \n         levels = 2:7, \n         labels = c(\"No degree\", \"Special education School\", \"Secondary School\",\n                    \"Intermediate secondary school\", \n                    \"Upper secondary\", \"Abitur\"))\n```\n:::\n\n\n\n+ Create the regression model using this new factor variable for `schul2_fct` as the independent variable.\n+ Change the reference category to *Intermediate secondary school* (`schul2` = 5) and estimate the model again.\n\n### Multiple Independent Variables & Coefficient Plot {#reg4}\n\n+ Adjust the `lm()` model `mod1` (with all cases from `pend_u08`) to include the education level (`schul2`) as an additional independent variable.\n+ Also create a graphical comparison of the two models with and without the education level.\n\n## Appendix\n\n\n### Visualizing Regression Lines and Data\n\nWith `geom_smooth(method = \"lm\")`, we can also represent regression lines in `{ggplot2}`:\n\nWe can visualize our model with `var1` and `var2` as follows:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_point(size = 2) + \n  geom_smooth(method = \"lm\")  \n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=288}\n:::\n:::\n\n\n\n\nHere, it appears we have an outlier. In our small dataset, it is easy to find. In larger datasets, `geom_text()` can help us:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_point(size = 2) + \n  geom_smooth(method = \"lm\")  +\n  geom_text(data = . %>% filter(var2 > 20), aes(y = var2 + 3, label = id), color = \"sienna1\")\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/graph2-1.png){fig-align='center' width=288}\n:::\n:::\n\n\n\n\nWe can also specify `geom_` for just a subset by reassigning `data =` (not using the selection from the main `ggplot()` command) and applying a `filter()`. Additionally, we shift the label slightly above the point with `var2 + 3`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1 <- dat1 %>% select(-matches(\"compl\"))\n```\n:::\n\n\n\n\n\n\n### Predicted Values {#pred}\n\nThe predicted values from `lm()` can be found under `$fitted.values`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1$fitted.values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2         3         4         5         6         7         8 \n 1.337972 -0.500994  1.337972  6.854871 10.532803 12.371769 14.210736  6.854871 \n```\n\n\n:::\n:::\n\n\n\nThese predicted values are simply the sum of the value under `Intercept` and the value under `var1` multiplied by the respective value for `var1`. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = var2 ~ var1, data = dat1)\n\nCoefficients:\n(Intercept)         var1  \n     -2.340        1.839  \n```\n\n\n:::\n:::\n\n\n\nFor the first row of `dat1`, the predicted value from `m1` is: `2.1351 + 0.5811 * 1 = `2.7162\n\nThe values under `fitted.values` follow the order in the dataset, so we can simply add them as a new column in `dat1`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$lm_predictions <- m1$fitted.values\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id var1 var2 educ gend  x ed_fct lm_predictions\n1  1    2    2    3    2  2   high       1.337972\n2  2    1    2    1    1  1  basic      -0.500994\n3  3    2    1    2    1  2 medium       1.337972\n4  4    5    9    2    2  4 medium       6.854871\n5  5    7    7    1    1  1  basic      10.532803\n6  6    8    4    3    2 NA   high      12.371769\n7  7    9   25    2    1 NA medium      14.210736\n8  8    5    3   -1    2 NA   <NA>       6.854871\n```\n\n\n:::\n:::\n\n\n\nThe plot shows how predictions based on `m1` look: They correspond to the values on the blue line (the so-called regression line) at the respective points for `var1`. \n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(dat1, aes(x = var1, y = var2)) +\n  geom_point(size = 3) +      \n  geom_smooth(method = \"lm\", color = \"darkblue\", se = FALSE, size = .65) +\n  geom_point(aes(x = var1, y = lm_predictions), color = \"dodgerblue3\", size = 3) +\n  expand_limits(x = c(0,8), y = c(0,8))\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=288}\n:::\n:::\n\n\n\n\n### Residuals {#res2}\n\nThe light blue points (i.e., the predictions from `m1`) are close to the actual points. However, even the light blue points do not perfectly overlap with the actual values. \nThese deviations between the predicted and actual values are called residuals:\n$$Residual = observed\\, value \\; - \\; predicted\\, value$$\n$$\\varepsilon_{\\text{i}} = \\text{y}_{i} - \\hat{y}_{i}$$\nWe can calculate these manually as the difference between the actual and predicted value or simply call them using `m1$residuals`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1$residuals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         1          2          3          4          5          6          7 \n 0.6620278  2.5009940 -0.3379722  2.1451292 -3.5328032 -8.3717694 10.7892644 \n         8 \n-3.8548708 \n```\n\n\n:::\n:::\n\n\n\nWe can also store the residuals for `lm` in `dat1`: \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat1$lm_residuals <- m1$residuals\ndat1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  id var1 var2 educ gend  x ed_fct lm_predictions lm_residuals\n1  1    2    2    3    2  2   high       1.337972    0.6620278\n2  2    1    2    1    1  1  basic      -0.500994    2.5009940\n3  3    2    1    2    1  2 medium       1.337972   -0.3379722\n4  4    5    9    2    2  4 medium       6.854871    2.1451292\n5  5    7    7    1    1  1  basic      10.532803   -3.5328032\n6  6    8    4    3    2 NA   high      12.371769   -8.3717694\n7  7    9   25    2    1 NA medium      14.210736   10.7892644\n8  8    5    3   -1    2 NA   <NA>       6.854871   -3.8548708\n```\n\n\n:::\n:::\n\n\n\n\nHere are the residuals for `lm` shown in light blue:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(dat1, aes(x = var1, y = var2)) + \n  geom_smooth(method = \"lm\", color = \"darkblue\", se = FALSE, size = .65) +\n  geom_segment(aes(x = var1, xend = var1, y = var2, yend = lm_predictions), color = \"dodgerblue3\", size = .65, linetype = 1) +\n  geom_point(size = 3) +\n  geom_point(aes(x = var1, y = lm_predictions), color = \"dodgerblue3\", size = 3) +\n  expand_limits(x = c(0,8), y = c(0,8))\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=264}\n:::\n:::\n\n\n\n\n### Checking Assumptions\n[Model Dashboard](https://easystats.github.io/easystats/reference/model_dashboard.html)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"performance\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\n\nmodel_test <- check_model(m4)\nplot(model_test)\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/reg02-1.png){width=672}\n:::\n:::\n\n\n\n\n### Test for Normal Distribution of Residuals\n\nGraphical check: Q-Q plot\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggfortify)\nautoplot(m1, which = 2)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=60%}\n:::\n:::\n\n\n\n\nYou can check the normality assumption with the Shapiro-Wilk test & `shapiro.test()`. This tests the null hypothesis $H_0$: \"The residuals are normally distributed\" against the alternative hypothesis $H_A$: \"The residuals significantly deviate from normal distribution.\"\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(m1$residuals) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  m1$residuals\nW = 0.95346, p-value = 0.746\n```\n\n\n:::\n:::\n\n\n\n\n### Test for Homoscedasticity\n\nHomoscedasticity is present when the predicted values are approximately equally distant from the actual values (`m1\\$fitted.values`) across the entire range of values. There is both a graphical method for checking this and a formal test. For the graphical check, the predicted values and the residuals are plotted as a scatterplot. The `autoplot()` function can be helpful here:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nautoplot(m1, which = 1)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](09_reg_files/figure-html/unnamed-chunk-39-1.png){fig-align='center' width=672 height=50%}\n:::\n:::\n\n\n\nThe associated test is the Breusch-Pagan test. This test evaluates the null hypothesis ($H_0$) of \"homoscedasticity\" against the alternative hypothesis ($H_A$) of \"heteroscedasticity.\" The p-value indicates the probability with which we must reject the homoscedasticity assumption. In R, you can use `bptest` from the `lmtest` package for this:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"lmtest\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmtest)\nbptest(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  m3\nBP = 3.6069, df = 2, p-value = 0.1647\n```\n\n\n:::\n:::\n\n\n\n\n### Test for Multicollinearity\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"car\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# library(car)\npendx <- haven::read_dta(\"./orig/PENDDAT_cf_W13.dta\",n_max = 300)  %>% filter(netges >0, palter >0 )\nmox <- lm(netges ~ palter + azges1, data=pendx)\ncar::vif(mox)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  palter   azges1 \n1.000133 1.000133 \n```\n\n\n:::\n:::\n\n\n\n\n- A common threshold for the Variance Inflation Factor (VIF) is 10. Values of VIF above 10 indicate a serious multicollinearity problem, and often measures are recommended starting from a stricter threshold of about 5.00. In this specific example, all independent variables are within acceptable limits according to both thresholds.\n- If multicollinearity is present, there are several ways to address it: We can exclude one or more independent variables from the model. This is ultimately a substantive question and cannot be resolved with a standard recipe. Alternatively, we can combine the collinear independent variables into index variables. For example, we could create a common index, such as the average of the respective independent variables.\n\n### Comparing Regression Models\n\nWith the `{performance}` package, we can also perform a comprehensive model comparison:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"performance\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\ncompare_performance(m1, m4, metrics = c(\"R2\", \"R2_adj\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWhen comparing models, please note that probably not all models were fit\n  from same data.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Comparison of Model Performance Indices\n\nName | Model |    R2 | R2 (adj.)\n--------------------------------\nm1   |    lm | 0.486 |     0.400\nm4   |    lm | 0.700 |     0.400\n```\n\n\n:::\n:::\n\n\n\n\n### Individual Coefficient Plots with `{broom}` {#broomplt}\n\n`modelplot()` offers a quick way to create coefficient plots, but I often use [`{broom}` ](https://broom.tidyverse.org/). Using `broom::tidy(..., conf.int = TRUE)`, we get a `data.frame` with the results of the regression model, which we can then process further in `{ggplot2}`—if the standard solution from [`modelplot()`](09_reg.qmd#modelplot) doesn't meet our needs or preferences:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(broom) ## already loaded as part of the tidyverse\ntidy(m3, conf.int = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  term         estimate std.error statistic p.value conf.low conf.high\n  <chr>           <dbl>     <dbl>     <dbl>   <dbl>    <dbl>     <dbl>\n1 (Intercept)      4.5       6.26     0.719   0.512    -12.9      21.9\n2 ed_fctmedium     7.17      8.08     0.887   0.425    -15.3      29.6\n3 ed_fcthigh      -1.5       8.85    -0.170   0.874    -26.1      23.1\n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(m3, conf.int = TRUE) %>% \n  mutate(term = str_replace(term, \"ed_fct\", \"Education: \")) %>% \n  ggplot(aes(y = term, x = estimate)) +\n  geom_vline(aes(xintercept = 0), linetype = \"dashed\", color = \"navy\") +\n  geom_errorbarh(aes(xmin = conf.low, xmax  = conf.high), height = .1) + \n  geom_point(color = \"orange\", shape = 18, size = 7) +\n  theme_minimal(base_size = 16)\n```\n\n::: {.cell-output-display}\n![](09_reg_files/figure-html/mod1_tidy-1.png){fig-align='center' width=90% height=50%}\n:::\n:::\n",
    "supporting": [
      "09_reg_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"site_libs/jsoneditor-0.18.7/jsoneditor.min.js\"></script>\n<script src=\"site_libs/jsonedit-binding-4.0.0/jsonedit.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}